### ISSUE TITLE
Can we create tutorials integrating Kafka with other tools such as Spark?

### ISSUE THREAD

**Issue by dgadiraju** [confluentinc/kafka-tutorials#120]
I come from Big Data background with deep expertise in Spark. Can we come up with tutorials integrating Kafka with Spark Structured Streaming?

**Comment by MichaelDrogalis** [comment]
Hey @dgadiraju -- thanks for asking! For the moment, we'd like to just keep the processing piece demonstrating vanilla Kafka, Kafka Streams, and KSQL. We're interested in expanding scope in the future, but for now, that's about as much as we can manage to maintain. 👍

**Comment by dgadiraju** [comment]
Dear Mike, Thank you for the response. I have asked my employee to contribute to Kafka Tutorials. She will focus on Kafka Streams and KSQL then.
