### ISSUE TITLE
Investigate KTs that could not be upgraded to CP 7.1.0/ AK 3.1.0

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#1256]
The PR https://github.com/confluentinc/kafka-tutorials/pull/1229 could not update a few KTs to target CP/AK versions and the failures were not well understood.

In order to not block the PR (which affects all KTs and needed to be pushed through), @bbejeck and I agreed to revert the changes for these specific KTs and use this GH issue to track investigating & updating them.

- https://github.com/confluentinc/kafka-tutorials/tree/master/_includes/tutorials/error-handling
- https://github.com/confluentinc/kafka-tutorials/tree/master/_includes/tutorials/naming-changelog-repartition-topics/kstreams

**Comment by bbejeck** [comment]
Fixed via https://github.com/confluentinc/kafka-tutorials/pull/1262
