### ISSUE TITLE
Topic name issue

### ISSUE THREAD

**Issue by marcin2x4** [confluentinc/kafka-tutorials#1268]
Where does 'ORDERS_ENRICHED' topic gets created?
I checked the ksql code but couldn't find in provided [files](https://github.com/confluentinc/kafka-tutorials/blob/master/_includes/tutorials/denormalization/confluent/code/tutorial-steps/dev/source.sql).

https://github.com/confluentinc/kafka-tutorials/blob/2cacde636a6036b80efd51c67ceea56167fa41b0/_includes/tutorials/denormalization/confluent/code/tutorial-steps/dev/sink.sql#L7

**Comment by ybyzek** [comment]
@marcin2x4 thanks for filing the issue. This may be a valid bug (IIRC the stream was renamed but the topic referenced in the connector was not).
