### ISSUE TITLE
New error: harness-runner distribution not found

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#1308]
```
pkg_resources.DistributionNotFound: The 'harness-runner==0.0.1' distribution was not found and is required by the application
```

See https://github.com/confluentinc/kafka-tutorials/pull/1307#issuecomment-1190612079 for details

**Comment by davetroiano** [comment]
We're no longer hitting this with the [move](https://github.com/confluentinc/kafka-tutorials/pull/1303) to self-hosted agents
