### ISSUE TITLE
build failure: rm: cannot remove 'kafka-tutorials/harness_runner/harness_runner.egg-info/top_level.txt': Permission denied

### ISSUE THREAD

**Issue by davetroiano** [confluentinc/kafka-tutorials#1324]
Semaphore build sometimes hits this error:

![image](https://user-images.githubusercontent.com/4550245/181285092-a92bcb38-bd18-43d4-a7c0-4a5139e8aa30.png)

**Comment by ybyzek** [comment]
@davetroiano I don't recall seeing this error before.  I could have just missed it but is this a new issue (cc: @bbejeck ) and if so, why is it surfacing now?

**Comment by davetroiano** [comment]
Won't fix, instead fixing #1326 which makes this moot
