### ISSUE TITLE
Aggregations: min/max (KStreams)

### ISSUE THREAD

**Issue by tlberglund** [confluentinc/kafka-tutorials#15]

**Comment by rspurgeon** [comment]
@colinhicks I'm going to assign myself this one as the kstreams implementation of this: https://kafka-tutorials.confluent.io/create-stateful-aggregation-minmax/ksql.html which is currently marked as "Help build it"... Does that work for you?

**Comment by colinhicks** [comment]
@rspurgeon, sgtm!
