### ISSUE TITLE
harness-runner produces garbled stdout requiring a terminal `reset` invocation

### ISSUE THREAD

**Issue by rspurgeon** [confluentinc/kafka-tutorials#156]
When running test harness on my terminal, the output of one of the stages (cannot be certain which), causes stdout printing garbage and if that stage fails it seems the terminal remains in a broken state which requires me to invoke a `reset` command.

> 
> Rick Spurgeon 4:57 PM
> Anyone else have issues with harness-runner “breaking” their terminal in such a way it requires a reset invocation to clear up garbled stdout?  I’m also seeing my test application continue to run beyond the life of the test harness process.   My test app continues pushing std out messages out to my terminal even though harness-runner has terminated making the terminal unusable.  I have to find the process and kill it in a second terminal to get my original terminal back.
> 
> michael.drogalis 4:58 PM
> @Rick Spurgeon Yeah I never got the stdout piece under control. That is my fault. On the process killing piece, that sounds like a bug. There’s a step in the harness runner that iterates all the open procs and kills them off.
> 
> colinh 4:59 PM
> stty sane
> try that
> 
> Rick Spurgeon 5:00 PM
> reset resolves the issue in my terminal, but looking to avoid it altogether
>

**Comment by bbejeck** [comment]
resolved via https://github.com/confluentinc/kafka-tutorials/pull/483
