### ISSUE TITLE
Produce and consume messages to a topic in Confluent Cloud with Confluent Cloud CLI

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#186]

**Comment by ybyzek** [comment]
To determine: 

* User provides pre-existing broker endpoint & credentials
* KT instructs user to create cluster & credentials using CLI
* KT instructs user to use https://github.com/confluentinc/examples/blob/5.5.0-post/ccloud/ccloud-stack/README.md or

**Comment by ybyzek** [comment]
Let's use `ccloud-stack` (as being done for https://github.com/confluentinc/kafka-tutorials/issues/451

**Comment by rspurgeon** [comment]
@ybyzek I scheduled this work for myself for the week of Aug 31-Sep 3 if you agree that's an ok timeline . ?

**Comment by ybyzek** [comment]
@rspurgeon SGTM 👍

**Comment by rspurgeon** [comment]
Better late than never, PR available #565

**Comment by ybyzek** [comment]
Resolved by https://github.com/confluentinc/kafka-tutorials/pull/565, closing GH issue
