### ISSUE TITLE
Using Kafka Stream KTable Foreign Key Joins

### ISSUE THREAD

**Issue by bbejeck** [confluentinc/kafka-tutorials#193]
With the implementation of [KIP-213](https://cwiki.apache.org/confluence/display/KAFKA/KIP-213+Support+non-key+joining+in+KTable) we can now do a `KTABLE-KTABLE` join with a foreign key (the join key is in the value of one of the KTables).

Foreign key joins aren't supported in KSQL yet.

**Comment by adamhrosenberg** [comment]
but this doesn't support stream to table FK joining? is the logical thing to do convert the stream to a table and join those on the fk? seems not ideal..

**Comment by chinthakadd** [comment]
Just curious. Is Foreign Key support for KStream-KTable Joins still not supported?

**Comment by sumati-kulkarni** [comment]
Hi, is there any update on this ask? "Just curious. Is Foreign Key support for KStream-KTable Joins still not supported?"
