### ISSUE TITLE
[KSQL] Create Tumbling WIndows tutorial

### ISSUE THREAD

**Issue by daveshook** [confluentinc/kafka-tutorials#210]
Section **Take it to production** fails due to the STREAM `ratings` and TABLE `ratings_count` already existing. To eliminate this error, add the following to the end of step 3 of section **Try it**:

Before continuing, we need to clean up our KSQL environment a bit in preparation for the next activities. We will DROP the stream and table that was created but we first have to TERMINATE the running query that is referenced by them.
```
LIST QUERIES;
```
You should see something like the following in response.
```
--------------------------------------------------------------------------------------------------------------------------------------------
CTAS_RATING_COUNT_0 | RATING_COUNT | CREATE TABLE RATING_COUNT WITH (KAFKA_TOPIC = 'rating_count', REPLICAS = 1, PARTITIONS = 1) AS SELECTRATINGS.TITLE "TITLE", COUNT "RATING_COUNT", WINDOWSTART() "WINDOW_START", WINDOWEND() "WINDOW_END"FROM RATINGS RATINGSWINDOW TUMBLING ( SIZE 6 HOURS ) GROUP BY RATINGS.TITLE; --------------------------------------------------------------------------------------------------------------------------------------------
```
The name of the query in the above example is `CTAS_RATINGS_COUNT_0`

Continue by running the following commands.
```
TERMINATE <query name>;
DROP TABLE rating_count;
DROP STREAM ratings;
```

**Comment by colinhicks** [comment]
@daveshook, as you pointed out separately, this clean-up suggestion would apply to all existing KSQL tutorials. However, there is also an undocumented assumption that users would not use the same environment for production, as for the dev and test steps. What are your thoughts on redefining this issue along the lines of: `Production section should indicate a fresh environment is required`?

**Comment by daveshook** [comment]
@colinhicks adding that comment would definitely be the easier path to take.

**Comment by daveshook** [comment]
I will close this issue and create another that uses the suggested definition.
