### ISSUE TITLE
Detecting and Analyzing Suspicious Network Activity

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#250]
Analyze network traffic in real time and drive alerts based on suspect patterns with KSQL.

label: NETWORKS

**Comment by awalther28** [comment]
This recipe covers windowing and selecting with `WHERE` and a `group by`.  It covers the same concepts as the [abnormal transactions KT](https://kafka-tutorials.confluent.io/anomaly-detection/ksql.html).
