### ISSUE TITLE
Inline Streaming Aggregation

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#255]
Enrich streaming events with KSQL to add measures such as average(), maximum() and minimum(), and emit an expanded event that includes the aggregated measures.

label: STREAMING ETL

**Comment by awalther28** [comment]
The content in this recipe is covered in the following KTs [aggregating sum](https://kafka-tutorials.confluent.io/create-stateful-aggregation-sum/ksql.html), [min/max](https://kafka-tutorials.confluent.io/create-stateful-aggregation-minmax/ksql.html)
