### ISSUE TITLE
Merging Streams

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#256]
Aggregate multiple streams into one with KSQL. In this example, you’ll get a stream and topic that has all of the purchase order events from two locations available for consumption.

label: NETWORKS

**Comment by awalther28** [comment]
This recipe's technical content is covered in the [merging many streams KT](https://kafka-tutorials.confluent.io/merge-many-streams-into-one-stream/ksql.html). We also have a KT on [multi-joins ](https://kafka-tutorials.confluent.io/multi-joins/ksql.html) that goes further on to talk about merging multiple streams and tables.
