### ISSUE TITLE
Counting Messages in a Topic

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#261]
Use KSQL to count messages in a topic.

label: ADMINISTRATION

**Comment by ybyzek** [comment]
https://www.confluent.io/stream-processing-cookbook/ksql-recipes/counting-messages-in-a-topic is #2 of all recipes in the stream processing cookbook

**Comment by ybyzek** [comment]
Also asked in [Slack|https://confluentcommunity.slack.com/archives/C488525JT/p1599304454361400]

**Comment by rmoff** [comment]
I'm planning to port [this](https://rmoff.net/2020/09/08/counting-the-number-of-messages-in-a-kafka-topic/) to a tutorial or two
