### ISSUE TITLE
Aggregating Data

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#266]
Build stateful aggregates on streaming data using KSQL.

label: STREAMING ETL

**Comment by awalther28** [comment]
The content in this recipe is covered in the following KTs [aggregating sum](https://kafka-tutorials.confluent.io/create-stateful-aggregation-sum/ksql.html) and [min/max](https://kafka-tutorials.confluent.io/create-stateful-aggregation-minmax/ksql.html)
