### ISSUE TITLE
Data Routing Joined with a KTable

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#267]
Perform data routing to specific topics described in a table using KSQL.

label: STREAMING ETL

**Comment by awalther28** [comment]
The IA team believes this recipe's technical content is already highlighted in the ["Join a Stream to a Table" KT](https://kafka-tutorials.confluent.io/join-a-stream-to-a-table/ksql.html) and that the recipe should be considered converted.
