### ISSUE TITLE
Enriching Streams with Static Data Loaded as a Table

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#270]
Enrich incoming streams with static data loaded as a table using a stream-table join.

label: STREAMING ETL

**Comment by awalther28** [comment]
[This KT](https://kafka-tutorials.confluent.io/join-a-stream-to-a-table/ksql.html) covers the technical content referred to in the recipe. [This PR](https://github.com/confluentinc/kafka-tutorials/pull/649) augmented the verbiage to talk about the database aspect of the recipe.
