### ISSUE TITLE
ATM Fraud Detection

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#271]
Take a Kafka topic of transaction events and identify transactions taking place on the same account within a short time period using KSQL.

label: ANOMALY DETECTION

**Comment by awalther28** [comment]
It is very similar in technical content to "DEVX-2184: Convert 'Detecting Abnormal Transactions'" recipe which is converted . We decided a comment mentioning the atm fraud use case in the [Anomaly Detection KT](https://kafka-tutorials.confluent.io/anomaly-detection/ksql.html) would suffice (which has already been done).
