### ISSUE TITLE
Detecting Unusual Credit Card Activity

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#272]
Spot a stolen credit card by aggregating credit card transactions over a time window using KSQL.

label: ANOMALY DETECTION

**Comment by awalther28** [comment]
It is very similar in technical content to "DEVX-2184: Convert 'Detecting Abnormal Transactions'" recipe which is converted . We decided a comment mentioning the unusual credit card activity use case in the [Anomaly Detection KT](https://kafka-tutorials.confluent.io/anomaly-detection/ksql.html) would suffice (which has already been done).
