### ISSUE TITLE
Create streamlined conversion workflow for existing KSQL Recipes

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#287]
We should explore some automation that allows us to:
- Reuse existing recipe content and code
- Add self-testability

**Comment by colinhicks** [comment]
To be clear, the idea is to use some tooling as an assist – in order to avoid doing everything by hand.

One path to consider is leveraging the current cookbook source, e.g. https://github.com/confluentinc/ksql-recipes-try-it-at-home/tree/master/creating-composite-key.

It may be reasonable to parse the markdown and other sources into the KT scheme.

**Comment by ybyzek** [comment]
@colinhicks @bbejeck  is this issue worth doing?  My leaning is no, for the following reasons:

1. One time use (yes, dozens of recipes, but it's still one bulk conversion and done)
2. Investment in tooling conversion that works is non-trivial
3. Main time/cycles is in building the ~60 files required for each KT, setting it up, creating test data, converting KSQL to ksqlDB syntax, creating tests, validation, etc

**Comment by colinhicks** [comment]
Yeah, no matter what, there is manual work to be done. This issue just captures the idea that we may be able to reduce the manual labor involved with some limited automation.

If these are the rough tasks per conversion:

1. Setting it up
1. Creating test data
1. Converting syntax
1. Creating tests
1. Validation

I was thinking some automation could help with 1. and possibly 2., because the recipe source has a consistent structure, including sample data. The automation could scaffold the KT file structure based on the recipe source.

The question is whether the overall reduction in marginal cost to convert individual tutorials is significantly greater than the effort it takes to build conversion automation. I'm not sure.

**Comment by ybyzek** [comment]
I think we get 1 and part of 2 with https://github.com/confluentinc/kafka-tutorials/blob/master/tools/clone-tutorial.sh .  But the angle is different: the scaffolding is from other KTs, not from the recipe.  And since the recipe could be changed anyway during migration, seems less valuable to invest in tooling there.

**Comment by awalther28** [comment]
After much review and time spent migrating recipes, we believe all of the recipes technical content has been migrated to the kafka-tutorials project. Given that, there is no need for a streamlined conversion workflow for the cookbook 😄 🎉
