### ISSUE TITLE
ksqlDB filtering tutorial is missing expected print topic output

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#374]
![image](https://user-images.githubusercontent.com/141130/81225880-f5921480-8fb7-11ea-9002-98f4f05cf68a.png)

We should render the expected output from the `PRINT` statement.

See also #367

**Comment by awalther28** [comment]
@colinhicks it looks like this may be resolved. Would you mind verifying? Link: https://kafka-tutorials.confluent.io/filter-a-stream-of-events/ksql.html Screenshot below:
<img width="1517" alt="Screen Shot 2020-10-07 at 3 45 25 PM" src="https://user-images.githubusercontent.com/12937975/95391360-2a323100-08b4-11eb-9ffa-9ba9c37cdd1b.png">

**Comment by colinhicks** [comment]
Verified. It was fixed in 2758210, but we forgot to close this issue.
