### ISSUE TITLE
Rename "Vanilla Kafka" tutorial type

### ISSUE THREAD

**Issue by rspurgeon** [confluentinc/kafka-tutorials#382]
The word Vanilla may not be widely known as a synonym to Basic or Standard (especially to new non-native English speakers).

Using the term Basic or Standard could reduce confusion for some new users coming to Kafka without deeper English vocabularies.

<img width="503" alt="Screen Shot 2020-05-19 at 9 10 59 AM" src="https://user-images.githubusercontent.com/10521262/82336888-b77df300-99b0-11ea-8220-ecc8017c98df.png">

**Comment by gAmUssA** [comment]
suggestions:

- base clients
- java API
- Core Kafka Clients (a personal favorite, thanks @stanislavkozlovski  for the suggestion)
