### ISSUE TITLE
Inconsistent usage of "docker-compose up" with and without "-d" option

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#385]
KT should have consistent usage of either "docker-compose up" or "docker-compose up-d", but right now it is a mix:

```
[16:14:34] ~/git/kafka-tutorials(master) ✗: grep -ir "docker-compose up" _includes/* | grep "up -d" | wc -l
28
[16:14:38] ~/git/kafka-tutorials(master) ✗: grep -ir "docker-compose up" _includes/* | grep -v "up -d" | wc -l
14
```

**Comment by gAmUssA** [comment]
@colinhicks @bbejeck I remember for some reason we switched from _daemon_ mode and I don't remember why...

**Comment by bbejeck** [comment]
> I remember for some reason we switched from daemon mode and I don't remember why...

@gAmUssA I think that discussion and switch happened before I joined the team.  I only remember discussions that we should **_move to_**  `docker-compose up -d`, so I can't add any context here.

**Comment by colinhicks** [comment]
Yes, the decision was to move to daemon mode exclusively. I am not aware of a previous decision to switch away from daemon mode to non-daemon mode. The current state reflects a transition in progress to `-d`.

Related:
#202
#383

**Comment by gAmUssA** [comment]
so let's find and replace then ;)

**Comment by bbejeck** [comment]
Completed via PR https://github.com/confluentinc/kafka-tutorials/pull/392
