### ISSUE TITLE
Enable users to run an individual KT automatically

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#386]
To enable users to run an individual KT automatically (not step-by-step), it can be done with `harness-runner` but is not well documented.  

This GitHub issue is to make it easier for users to do so.  The "fix" can involve a multi-pronged approach:

1. Elaborate on usage of `harness-runner` in the README in GH
2. For each KT itself that is rendered to kafka-tutorials.confluent.io, add a link to the GH README explanation on how to checkout source code and run `harness-runner`
3. Make it easier to install/run `harness-runner`: "Also, if I remember correctly the harness runner requires to install some python deps, maybe it can be packaged as a docker image to avoid having to deal with that?"

At minimum this GH issue can address item 1 and then we can file separate GH issues to track items 2 and 3

**Comment by bbejeck** [comment]
Closing this umbrella issue as we now have #403, #404, and #405 tracked separately.
