### ISSUE TITLE
Semaphore process doesn't shutdown on test exit

### ISSUE THREAD

**Issue by bbejeck** [confluentinc/kafka-tutorials#396]
Sometimes the semaphore process for a test doesn't terminate even though the test executed successfully.  Eventually, semaphore marks the test as a failure due to timeout.  This situation makes it hard to determine when there are a potential regression and forces team members to drill into the results to inspect the failures.

**Comment by bbejeck** [comment]
I believe this issue is related to https://github.com/confluentinc/kafka-tutorials/issues/156

One possible solution is to replace `slf4j-simple:1.7.26.jar` in the Streams `build.gradle` file.  The `slf4j.SimpleLogger` logs everything to `StdErr`.  It would be worth seeing if, by logging to a file, we can eliminate the garbled `stdout`, which requires a reset when running locally and seems to cause harness test run failures during semaphore builds.

Also, it may prove useful to have the logs available in a file for debugging, etc.

**Comment by ybyzek** [comment]
@bbejeck thanks for the heads up that this may impact users running KTs locally.

**Comment by gAmUssA** [comment]
@bbejeck how to reproduce this locally?

**Comment by bbejeck** [comment]
> @bbejeck how to reproduce this locally?

The garbled `stdout` happens when running `make` locally with some of the tutorials.  I'm convinced the semaphore time-out failures (the test passes but doesn't exit, hence the timeout) are related to this.  This issue has been around for a while see issue #156.

**Comment by bbejeck** [comment]
>One possible solution is to replace slf4j-simple:1.7.26.jar in the Streams build.gradle file. The slf4j.SimpleLogger logs everything to StdErr. It would be worth seeing if, by logging to a file, we can eliminate the garbled stdout, which requires a reset when running locally and seems to cause harness test run failures during semaphore builds.

I tried this approach and it didn't improve anything.

**Comment by bbejeck** [comment]
resolved via #483
