### ISSUE TITLE
Changing the number of partitions and replicas of a Kafka topic

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#446]
Changing number of partitions using ksqlDB
Show the recommended steps to change the number of partitions.
	
This is one possible example in case the producers can be stopped (open for discussion):

Stop producers
Run the ksqlDB query:	

```		
CREATE STREAM old WITH (KAFKA_TOPIC='old-topic',VALUE_FORMAT='JSON');
CREATE STREAM new WITH (KAFKA_TOPIC='new-topic',VALUE_FORMAT=’JSON',PARTITIONS=12)  AS SELECT * FROM old EMIT CHANGES;
```

Check all data has been migrated
Increase number of consumers in the consumer group
Change topic subscription of the consumer group to new-topic (auto.offset.reset=’latest’)

cc: @SrWaves

**Comment by ybyzek** [comment]
@rmoff @bbejeck if we created this KT, and included changing both partition count and replica count, would it be ok to retire https://www.confluent.io/stream-processing-cookbook/ksql-recipes/repartitioning-changing-replication ?

**Comment by rmoff** [comment]
Yes, sounds good. 

minor nit: You don't need to respecify `VALUE_FORMAT` in the output if you're not changing it from the input AFAIK

**Comment by ybyzek** [comment]
KT added via https://github.com/confluentinc/kafka-tutorials/pull/470
