### ISSUE TITLE
Remove deprecated cp-enterprise-kafka: replace with cp-server or cp-kafka

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#461]
cp-enterprise-kafka is deprecated

**Comment by tlberglund** [comment]
Similar to my thinking in #460, this could lead to some perception problems. I realize `cp-server` is the natural migration from the deprecated `cp-enterprise-kafka`, but it might be better to use an OSS Kafka image when possible. When it's not possible, and we're writing tutorials for `cp-server`, then let it rip. Is that possible?

**Comment by ybyzek** [comment]
Has using `cp-enterprise-server` created perception problems?

**Comment by tlberglund** [comment]
It has not, but it also predated the Confluent Server product, which is a bigger line in the sand between OSS and Commercial features. `cp-server` will likely fly under the radar in almost all cases as well, but I would still argue that we stay faithful to the name and intent of the site and use Confluent Server only when we are actually using it.

**Comment by gAmUssA** [comment]
my $0.02
All tutorials should use cp-kafka by default and cp-server only if needed to showcase commercial features.

Also, will #462 shim work in this case?

**Comment by ybyzek** [comment]
@gAmUssA yes, #462 should work even with cp-kafka because of the override: https://github.com/confluentinc/kafka-tutorials/blob/master/tools/docker-compose.override.yml#L30 (assuming all docker-compose.yml files call the broker container `broker`)

**Comment by ybyzek** [comment]
Resolved by https://github.com/confluentinc/kafka-tutorials/pull/579
