### ISSUE TITLE
Create tl;dr answer one-liner at top of each KT

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#538]
Suggestion: Create tl;dr answer one-liner at top of each KT

Value:

1. For users who know they want the quick answer one-liner
2. Helps users find the information in the tutorial (which can be verbose)
3. SEO question/answer format
4. Potential: Minimum required KT is the one-liner answer, the rest of tutorial can be developed asynchronously

**Comment by ybyzek** [comment]
<img width="1487" alt="Screen Shot 2020-09-16 at 11 23 07 AM" src="https://user-images.githubusercontent.com/12448600/93358036-00cf3980-f80f-11ea-87e1-1182a3c53bee.png">

**Comment by rmoff** [comment]
+1 I think this is a good idea. 

The verbosity of the tutorials is a strength but for sure there are several of them (probably not all) where a tl;dr would really help. 

I wonder if it wouldn't make sense on all of them though. A tl;dr should be genuinely short (one sentence, maybe two), and not just a bleeding paragraph lifted from the article content.

**Comment by ybyzek** [comment]
<img width="524" alt="Screen Shot 2020-09-16 at 21 05 25 PM" src="https://user-images.githubusercontent.com/12448600/93407520-68fa3b80-f860-11ea-851c-2e86a3b75cf3.png">

<img width="1470" alt="Screen Shot 2020-09-16 at 21 05 20 PM" src="https://user-images.githubusercontent.com/12448600/93407529-6d265900-f860-11ea-9c9b-390c558e555b.png">

**Comment by ybyzek** [comment]
<img width="1506" alt="Screen Shot 2020-09-16 at 21 21 52 PM" src="https://user-images.githubusercontent.com/12448600/93408511-c42d2d80-f862-11ea-8a0e-222376f5174d.png">

<img width="696" alt="Screen Shot 2020-09-16 at 21 21 40 PM" src="https://user-images.githubusercontent.com/12448600/93408514-c68f8780-f862-11ea-9217-e852d4f80d18.png">

**Comment by ybyzek** [comment]
@rmoff @gAmUssA @bbejeck @awalther28 @rspurgeon @colinhicks @tlberglund -- we discussed today moving the Answer to be right below the Question.  I investigated this and discovered two concerns with this approach:

1. Any given question will have many answers, one for each tutorial type: ksqlDB, Kafka Streams, Basic Kafka.  And that tutorial type isn't selected until further down the tutorial.  We could toggle the answer based on what's selected below, but a user may be confused and dismiss a tutorial based on the answer type (e.g. user is looking for ksqlDB answer but sees Kafka Streams, so they leave).

2. I may just not be seeing how to do this, but reusing the same file for the answer doesn't seem possible.  It would have to be copied.

As a result of these two issues, the easiest way to proceed would be to leave the answer placement where it is in the PR, but just rename it to `tl;dr`. 

Thoughts?

**Comment by rmoff** [comment]
Good point on the primary concern, I agree that this could be confusing. 
I'm +1 on continuing with the placement where it is, but I feel strongly that it should be `tl;dr` and not "answer" / "short answer".

**Comment by ybyzek** [comment]
@rmoff As updated in the PR, here's a new presentation of it

<img width="614" alt="Screen Shot 2020-10-01 at 12 54 00 PM" src="https://user-images.githubusercontent.com/12448600/94839664-4c740c80-03e5-11eb-8b56-6a8d7b32d02f.png">

**Comment by rspurgeon** [comment]
> @rmoff As updated in the PR, here's a new presentation of it
> 
I'm sure it's tough to design, but I still think the actual solution visible in the first half of the first visible page would be most ideal.

**Comment by ybyzek** [comment]
@rspurgeon rspurgeon I played with this in https://github.com/confluentinc/kafka-tutorials/pull/540 and pulled in the `tl;dr` up and out of the TOC.  Would you mind taking a look at the PR and letting me know what you think?  (I'll post staging link when available, otherwise please checkout locally and render)

**Comment by bbejeck** [comment]
@ybyzek thanks for staging.  

+1 from me on the new placement of `tl;dr`.  

For your secondary concern from https://github.com/confluentinc/kafka-tutorials/issues/538#issuecomment-701706485, reusing the same answer could be difficult as some tutorials don't have a concise answer.  

But I don't have any suggestions for this ATM.

**Comment by rspurgeon** [comment]
@ybyzek I also think this latest version is better.  As you've done, if we can (at least) get the `tl;dr` header into view the "quick searcher" might find what they are looking for without navigating away.

> Secondary concern: I may just not be seeing how to do this, but reusing the same file for the answer (as used in the tutorial) doesn't seem possible. It would have to be copied, and this duplication is prone to errors.

Does placing it after the "Code Example:" section remove this concern?  I don't understand the technical bits here well enough to follow this particular concern.

**Comment by ybyzek** [comment]
The latest changes in this PR

* places the `tl;dr` after the user selects their choice (Kafka/ksqlDB/Streams) in Code Example, so hopefully that addresses the concern. 
* is much more visible because it's out of the ToC and in its own standalone section
* is optional -- KT-developers are recommended to add the `tl;dr` but it's not required, especially if there is no concise answer (to address @bbejeck 's point).  
* the answer _can_ reuse existing files to avoid duplicating code.  

What do y'all think?

**Comment by rspurgeon** [comment]
Sounds like a good solution to me

**Comment by ybyzek** [comment]
Structural changes provided by https://github.com/confluentinc/kafka-tutorials/pull/540

Now we need to go through all the tutorials and add in short answers ;)
