### ISSUE TITLE
Automatically build staging docs for every PR

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#567]
Currently for PRs: if there are N reviewers, then to view the rendering of KT, all 3 reviewers need to checkout the PR/branch and build locally.  

Proposal: it would be helpful if staging docs were built automatically so reviewers can all look at staging without building locally. It would get rebuilt every time there’s a commit to the PR.

Workaround: PR submitters (or reviewers) can manually trigger staging and then share out the staging link.

![image (16)](https://user-images.githubusercontent.com/12448600/94750233-98767100-0353-11eb-81f5-ef908f983eb0.png)

**Comment by ybyzek** [comment]
@bbejeck pointed out we should take into consideration some kind of clean up policy: "one thing we need to check if staging a PR deletes a previously staged build."

**Comment by bbejeck** [comment]
I have some additional comments I wanted to put down. 

There are other types of PRs we probably don't deploy automatically:
 

1. Dependabot dependency update PRs
2. Minor PRs updating configs etc.

From a quick scan of the Semaphore documentation about [build promoptions](https://docs.semaphoreci.com/reference/pipeline-yaml-reference/#promotions), I think this is something we can manage.

The other point to consider is retrieving the URL of the staged deployment is right now a manual process.  It would be good to investigate and see if it's possible to have that staged deployment URL published as a PR comment.

**Comment by ybyzek** [comment]
@colinhicks do you have visibility on the cost for generating staging docs for each PR?  By cost, literally $$ (S3), and any other cost that might be incurred.

**Comment by bbejeck** [comment]
Resolved via https://github.com/confluentinc/kafka-tutorials/pull/576
