### ISSUE TITLE
UDF (KSQL)

### ISSUE THREAD

**Issue by jwfbean** [confluentinc/kafka-tutorials#58]
"Mark Teehan [5:20 PM]
A prospect needs a replace() UDF to replace special characters in kSQL.  I'm not a java coder. They cannot do this in an SMT so kSQL is the next best option. Ideally a UDF that accepts an ASCII code (these are unprintable), and one that can be nested. Does anyone know of a suitable UDF chunk of code that I can use as a starting point?"

**Comment by colinhicks** [comment]
closed in #170
