### ISSUE TITLE
Update KTs with latest client code (e.g. kafka-streams-avro-serde)

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#582]
This issue surfaced in the conversation in https://github.com/confluentinc/kafka-tutorials/pull/579

For example:

```
implementation "io.confluent:kafka-streams-avro-serde:5.5.1"
```

Additional input from @bbejeck 

> Another point to consider is the kafka-streams-avro-serde:XXX dependency pulls in the corresponding AK version of kafka-clients as a transitive dependency. Kafka streams require kafka-clients as well, and those versions need to match.

> So if we upgrade the serde versions to 6.0.0, we'll need to make sure we update Kafka Streams to 2.6 as well.

> The previous versions of the serdes should work ok with the newer version of SR, so I vote to upgrade in a separate PR.

**Comment by bbejeck** [comment]
@ybyzek yes this issue is resolved by #949, I'm closing this issue.
