### ISSUE TITLE
Clicking on "Scala" button results in XML error

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#715]
Reproduce:

* From the page https://kafka-tutorials.confluent.io/produce-consume-lang/scala.html 
* Click on Scala button

Error results:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>286272CA6AF52F09</RequestId>
<HostId>
kLncjoBQpJgoNXc33Tpa0lSooCvdTRVSbOXwBsm2GfAwxjqTSwto4609vNdBew4xxHgCU2FxztA=
</HostId>
</Error>
```

cc: @gAmUssA @bbejeck

**Comment by gAmUssA** [comment]
Error from aws. Maybe file is missing on s3 bucket?

**Comment by bbejeck** [comment]
I'm looking into this.  It's strange as the tutorial itself renders, so clicking on the `Scala` button should just redirect back to the existing tutorial
