### ISSUE TITLE
Remove deprecated "--broker-list" and update document to use "--bootstrap-server"

### ISSUE THREAD

**Issue by saurabh-slacklife** [confluentinc/kafka-tutorials#722]
The Kafka Tutorial Document [Console Producer and Consumer Basics, no (de)serializers](https://kafka-tutorials.confluent.io/kafka-console-consumer-producer-basics/kafka.html) uses deprecated options **"--broker-list"**

Update to use **"--bootstrap-server"**

PS: I'm willing to update if the bug is accepted.

Thanks.

**Comment by ybyzek** [comment]
@saurabh-slacklife thank you for surfacing this!  It is true that `broker-list` is deprecated, in favor of `bootstrap-server`.

There are a few tutorials that use the deprecated form, in total 45 instances.  So the impact is bigger than just https://kafka-tutorials.confluent.io/kafka-console-consumer-producer-basics/kafka.html .  This GitHub issue should track changing all of them.  We are happy to do that, unless you want to.

**Comment by saurabh-slacklife** [comment]
@ybyzek Indeed the tutorial contains this at quite number of places (thanks for the number). I'm willing to do the change and will have a single PR for same.

Thanks.

**Comment by ybyzek** [comment]
Merged via https://github.com/confluentinc/kafka-tutorials/pull/723
