### ISSUE TITLE
kafka-streams-schedule-operations tutorial is empty

### ISSUE THREAD

**Issue by cassioseffrin** [confluentinc/kafka-tutorials#804]
Hello,

There is an absolute great tutorial here: https://kafka-tutorials.confluent.io/kafka-streams-schedule-operations/kstreams.html linking to this repo https://github.com/confluentinc/kafka-tutorials/tree/master/tutorials/kafka-streams-schedule-operations.

However It's a empty directory. It's possible to commit the source there?

**Comment by gAmUssA** [comment]
If you're looking source code for this tutorial it's here 

https://github.com/confluentinc/kafka-tutorials/tree/master/_includes/tutorials/schedule-ktable-ttl/kstreams/code

**Comment by cassioseffrin** [comment]
Thks @gAmUssA ! I am closing this issue!
