### ISSUE TITLE
Add "test" to Datagen tutorial link titles for clarity

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/kafka-tutorials#843]
![image](https://user-images.githubusercontent.com/48225759/117869913-3e764c00-b250-11eb-9160-a0a5e4a3c50e.png)

I had a brain fart when I saw these "generate data" tutorials and then after I looked into them it was clear it was for generating test/mock/dummy data. Maybe "generate data" -> "generate test data" in the titles? That would have cleared it up for me. Super important tutorials for users! Datagen is awesome.

**Comment by SivaTharun** [comment]
@chuck-confluent can i work on this issue, it would be great, if you can add more details about adding test to the Datagen tutorial.

**Comment by chuck-confluent** [comment]
@SivaTharun Thanks! I literally just mean adding the word "test" in the titles. Like, "Generate test data in a local cluster" rather than "Generate data in a local cluster"

**Comment by ybyzek** [comment]
This will be addressed by #856
