### ISSUE TITLE
Clipboard copy icon should have tooltip & provide visual feeedback

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-tutorials#87]
To make it clearer to the user, the clipboard copy icon should have

1. a tooltip saying what it does
2. a little 'copied!' hovertip when it's clicked which disappears after a couple of seconds

at the moment clicking it selects all the text, but as an end user I'm not sure if it's copied it to my clipboard, or if it was just selecting all the text for me and now I need to copy it.

**Comment by hartantothio** [comment]
@MichaelDrogalis - sorry, just saw this. We're currently won't be able to take on this at the moment as we're busy with other high priorities. However, if this is something urgent, please escalate to Rob.
