### ISSUE TITLE
Community contribution ✨banner renders improperly

### ISSUE THREAD

**Issue by rspurgeon** [confluentinc/kafka-tutorials#950]
Note the light on light text for the banner above the "Produce and Consume Records..."

![image](https://user-images.githubusercontent.com/10521262/135105245-bbdb1ca2-0988-40f3-a303-001dc3c63d5a.png)

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-948/produce-consume-lang/scala.html

**Comment by ybyzek** [comment]
It is now fixed, closing GH issue
