### ISSUE TITLE
Cloud icons in hero

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-tutorials#977]
Including the cloud vendor logos is nice, I would suggest three changes: 

1. They are too small - make them bigger
2. Include ALT text
3. Link to the respective vendor marketplace (as https://www.confluent.io/confluent-cloud/tryfree/ does) instead of `https://www.confluent.io/confluent-cloud/tryfree/`

![image](https://user-images.githubusercontent.com/3671582/140148406-649acd04-2d37-481b-b83d-575a65467bcc.png)

**Comment by ybyzek** [comment]
Tutorials have moved and hero updated: cloud icons are gone: https://developer.confluent.io/tutorials/index.html
