### ISSUE TITLE
Add asciidoctor styles

### ISSUE THREAD

**Issue by gAmUssA** [confluentinc/kafka-tutorials#98]
asciidoctor has few particular useful markup element
- admonitions blocks 
- callouts

we need to support those styles like it shown in jekyll-asciidoctor quickstart 

https://github.com/asciidoctor/jekyll-asciidoc#font-based-admonition-and-inline-icons

https://github.com/asciidoctor/jekyll-asciidoc-quickstart/tree/master/css

**Comment by hartantothio** [comment]
HI @gAmUssA - I know you DM'ed me but haven't gotten chance to work on this. We're very busy right now with other high priorities. However, if this is something urgent, please escalate to Rob.

**Comment by gAmUssA** [comment]
also kbd macro doesn't work `kbd:[Ctrl + C]`

**Comment by gAmUssA** [comment]
@hartantothio I created a test branch for you with «standard» asciidoctor file https://github.com/gAmUssA/kafka-tutorials/commit/0ffbeda9e53b1580f4cd8e1c4c8e9aa54a412bee
